version: '3.8'

services:
  netease-api:
    image: binaryify/netease_cloud_music_api:latest
    container_name: netease-music-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - music-metadata-network

networks:
  music-metadata-network:
    driver: bridge
