# AI Agent Documentation Review Configuration
# Project-specific overrides for the standard documentation review system
#
# NOTE: Standard context files are hardcoded in the script:
#   - AGENTS.md
#   - docs/DOCUMENTATION_MANAGEMENT.md
#   - docs/NAMING_CONVENTIONS.md
#
# This file is for project-specific customizations only.

# Agent to use (gemini-cli, codex-cli, claude-cli)
agent: "gemini-cli"

# Timeouts (seconds) - Override defaults if needed
timeouts:
  quick: 10
  standard: 30
  deep: 60

# Project-specific check customizations
# (Add custom checks here if your project needs additional validation)
custom_checks: []
  # Example:
  # - name: "API Documentation Sync"
  #   level: "standard"
  #   prompt: |
  #     Check if API documentation matches the OpenAPI spec...

# Exclusions (files to skip during review)
exclude_patterns:
  - "docs/archive/**"
  - "**/*-template.md"

# Environment variables
env:
  # Set DOC_AI_CHECK=false to disable AI checks
  enable_check: "${DOC_AI_CHECK:-true}"

  # Agent-specific settings
  gemini_model: "gemini-pro"
  codex_model: "gpt-4"

  # Verbosity
  verbose: "${DOC_CHECK_VERBOSE:-false}"

# Output settings
output:
  format: "console" # console, json, markdown
  save_to_file: false
  file_path: ".doc-review-result.txt"

  # Color output
  colors:
    pass: "green"
    warning: "yellow"
    fail: "red"
